# Homework 5

**Complete the coding questions in this notebook, and use your results to answer *Lab Homework 5* on bCourses**

For this homework we will be using the data: "Ziprecruiter.csv"

**Bold text is the actual Homework Quiz question.**

----

In [57]:
# Load required packages

library(dplyr)
library(purrr)
library(ggplot2)


Load in the data.

In [58]:
# Load the data

ZipRecruiter <- read.csv("Ziprecruiter.csv")

head(ZipRecruiter)

price signup revenue
1  39   1      39     
2 159   0       0     
3 299   0       0     
4  79   0       0     
5  99   0       0     
6  79   0       0

We will consider what would have happened if we had chosen an alternative price of \\$159 rather than \\$249 in our hypothetical, smaller scale experiment.

**Q1. In the original experiment, what is standard deviation of `revenue` when the price is \\$99 or \\$159? Round to the nearest whole dollar.**

In [59]:
ZipRecruiter %>%
    filter(price == "99" | price == "159") %>%
    summarize("SD" = sd(revenue))

print("STDEV of revenue is $54")


SD      
1 53.93609

[1] "STDEV of revenue is $54"


**Q2. In the original experiment, what is effect size on revenue for a price of \\$159? Measure the effect size in DOLLARS, and round to the nearest whole dollar.**

In [60]:
model = lm(revenue ~relevel(as.factor(price), ref ="99"), data = ZipRecruiter)
summary(model)

print("Effect size is 8/54 = .148")


Call:
lm(formula = revenue ~ relevel(as.factor(price), ref = "99"), 
    data = ZipRecruiter)

Residuals:
   Min     1Q Median     3Q    Max 
-43.91 -35.81 -22.92  -6.84 355.09 

Coefficients:
                                         Estimate Std. Error t value Pr(>|t|)
(Intercept)                               23.7600     2.4196   9.820  < 2e-16
relevel(as.factor(price), ref = "99")19  -16.9162     3.4283  -4.934 8.21e-07
relevel(as.factor(price), ref = "99")39  -11.2877     3.4081  -3.312 0.000930
relevel(as.factor(price), ref = "99")59   -7.8382     3.4293  -2.286 0.022303
relevel(as.factor(price), ref = "99")79   -0.8425     3.3730  -0.250 0.802757
relevel(as.factor(price), ref = "99")159   8.0400     3.4607   2.323 0.020193
relevel(as.factor(price), ref = "99")199  12.0498     3.4459   3.497 0.000473
relevel(as.factor(price), ref = "99")249  18.5733     3.4820   5.334 9.87e-08
relevel(as.factor(price), ref = "99")299  15.0865     3.4642   4.355 1.35e-05
relevel(as.factor(price), 

[1] "Effect size is 8/54 = .148"


**Q3. Consider a smaller scale experiment as we did in Lab 5, where we only include prices of \\$99 and \\$159 and include 120 customers per price rather than 800. For this experiment, what is the power associated with the effect size you reported in Q2? As in lab, use a significance level of 0.05, remember to convert the effect size into standard deviations, and round power to two decimal places.**

In [61]:
#what are results using 15% sample?
sample <- ZipRecruiter %>%
    filter(price == "99" | price == "159")%>%
    slice_sample(prop = 0.15, replace = FALSE)

#re-estimate regression using sample
sample_model <-lm(sample$revenue ~ sample$price)

summary(sample_model)

power.t.test(n=120, delta=.148, sd=1 , sig.level=.05)
print("Power is .2066")


Call:
lm(formula = sample$revenue ~ sample$price)

Residuals:
   Min     1Q Median     3Q    Max 
-27.08 -27.08 -24.46 -24.46 134.54 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)  
(Intercept)  31.39231   14.83369   2.116   0.0354 *
sample$price -0.04359    0.11200  -0.389   0.6975  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 51.4 on 232 degrees of freedom
Multiple R-squared:  0.0006525,	Adjusted R-squared:  -0.003655 
F-statistic: 0.1515 on 1 and 232 DF,  p-value: 0.6975



     Two-sample t test power calculation 

              n = 120
          delta = 0.148
             sd = 1
      sig.level = 0.05
          power = 0.2066263
    alternative = two.sided

NOTE: n is number in *each* group


[1] "Power is .2066"


**Q4. Since our hypothetical experiment is underpowered, we are likely to:**

(a) Get a false positive (i.e., make a Type I error), that is, to conclude that there is an effect when there actually isn't an effect. 

(b) Get a false positive (i.e., make a Type I error), that is, to conclude that there is no effect when there actually is an effect. 

(c) Get a false negative (i.e., make a Type II error), that is, to conclude that there is no effect when there actually is an effect. 

(d) Get a false negative (i.e., make a Type II error), that is, to conclude that there is an effect when there actually isn't an effect.

In [70]:
print("C")

[1] "C"


**Q5. What significance level would we need for our hypothetical experiment to have power of 0.8? Round to two decimal places.**

In [63]:
power.t.test(n=120, delta=.148, sd=1 , power=.8, sig.level=NULL)
print("Significance level is .7606 or 76.06%")


     Two-sample t test power calculation 

              n = 120
          delta = 0.148
             sd = 1
      sig.level = 0.7606452
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group


[1] "Significance level is .7606 or 76.06%"


**Q6. What sample size per price would we need for our hypothetical experiment to have power of 0.8? Use a significance level of 0.05 and round to the nearest whole number.**

In [64]:
power.t.test(n=NULL, delta=.148, sd=1 , power=.8, sig.level=.05)
print("Need 718 samples")


     Two-sample t test power calculation 

              n = 717.6234
          delta = 0.148
             sd = 1
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group


[1] "Need 718 samples"


**Q7. Suppose that, when evaluating the experiment using a regression, we include baseline customer-level control variables that reduce the residual standard deviation of `revenue` by 50%. Now what sample size per price would we need for our hypothetical experiment to have power of 0.8?**

In [65]:
power.t.test(n=NULL, delta=.296, sd=1 , power=.8, sig.level=.05)
print("Need 180 samples")


     Two-sample t test power calculation 

              n = 180.1309
          delta = 0.296
             sd = 1
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group


[1] "Need 180 samples"


Now let's return to analyzing the original ZipRecruiter experiment (rather than our hypothetical, smaller scale experiment.)

**Q8. What is the standard deviation of `revenue`, including all prices? Round to the nearest whole dollar.**

In [66]:
sd(ZipRecruiter$revenue)
print("$69")

[1] 69.49219

[1] "$69"


**Q9. What is the MDE of the original experiment for any given price? Report the MDE in DOLLARS, and round to the nearest whole dollar.**

In [67]:
power.t.test(n=800, delta=NULL, sd=1 , power=.8, sig.level=.05)
print("Delta is .14 SD, so MDE is .14*69 = 10")


     Two-sample t test power calculation 

              n = 800
          delta = 0.14019
             sd = 1
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group


[1] "Delta is .14 SD, so MDE is .14*69 = 10"


**Q10. What sample size would have been required to achieve an MDE of \\$1 in revenue per prospective customer? Round to nearest whole number.**

In [68]:
power.t.test(n=NULL, delta=.0145, sd=1 , power=.8, sig.level=.05)
print("Requires 74663 samples")


     Two-sample t test power calculation 

              n = 74663.31
          delta = 0.0145
             sd = 1
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group


[1] "Requires 74663 samples"


**Q11. ZipRecruiter ultimately decided to change their price from \\$99 to \\$249 based on the experiment. Test whether the difference in `revenue` for `price` = \\$249 and `price` = \\$399 is statistically significant. What is the p-value associated with this test? Round to two decimal places.**

In [69]:

sample1 <- ZipRecruiter %>%
    filter(price == "249")


sample2 <- ZipRecruiter %>%
    filter(price == "399")


t.test(sample1$revenue,sample2$revenue, var.equal = TRUE)
print("P-value is .7841")




	Two Sample t-test

data:  sample1$revenue and sample2$revenue
t = -0.27405, df = 1472, p-value = 0.7841
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -12.833044   9.686781
sample estimates:
mean of x mean of y 
 42.33333  43.90646 


[1] "P-value is .7841"
